device: sky
enableShutdownFunc: true
showCenterInfo: false

positions:
  important_info:
    size: 150
    x: 10
    y: 10
  expand_info:
    size: 150

import_info:
  # PCB SN
  - type: property
    name: pcb_sn
    key_name: a
    command: ro.ril.oem.sno

  # Battery level
  - type: battery
    name: battery_level
    key_name: b

  # MEID, if the phone supports CDMA, it must have the value
  - type: telephony
    name: meid
    key_name: g

  # Factory ID
  - type: property
    name: factory_id
    key_name: o
    command: ro.ril.factory_id

  # Software version
  - type: software_version
    name: software_version
    key_name: v

check_info:
  # Secure boot status
  - type: property
    name: secure_boot
    key_name: a
    command: ro.boot.secureboot
    pass_value: 1

  # Whether the bootloader lock is locked
  - type: property
    name: bootloader_lock
    key_name: b
    command: ro.boot.verifiedbootstate
    pass_value: green

  # RPMP provision
  - type: property
    name: rpmp
    key_name: c
    command: vendor.sys.rpmb_state
    pass_value: 23

  # Hardware version
  - type: property
    name: hardware_version
    key_name: m
    command: ro.boot.hwlevel
    pass_value: MP

  # Camera calibrate status check
  - type: camera
    name: camera_calibrate
    key_name: u
    command: persist.vendor.camera.mi.dualcal.state
    params:
      SKY2: 3
      OTHER: 0

  # Debug policy
  - type: property
    name: debug_policy
    key_name: l
    command: ro.boot.dp
    pass_value: 0xB

  # Security Key: FIDO
  - type: security
    name: fido
    key_name: h

  # Security Key: IFAA
  - type: security
    name: ifaa
    key_name: g

  # Digital rights management key: Widevine
  - type: security
    name: widevine
    key_name: q

  # Android Key box, services for DRM(Digital Rights Management)
  - type: security
    name: key_box
    key_name: t

  # Airplane mode check
  - type: modem
    name: airplane_mode
    key_name: Y
    command: settings get global airplane_mode_on
    pass_value: 0


  # NFC function check
  - type: nfc
    name: nfc
    key_name: B

  # Check for residual test pictures
  - type: picture
    name: picture
    key_name: p

  # Check if Modem NV info exists
  - type: property
    name: nv_back
    key_name: w
    command: persist.radio.goldencopy_flag
    pass_value: true

  # Sdcard status check
  - type: sdcard
    name: sdcard
    key_name: v

  # SIM card status
  - type: sim_card
    name: sim_card
    key_name: o
    command: gsm.sim.state
    params:
      DSDS: ABSENT,ABSENT
      SSSS: ABSENT
      JAPAN: ABSENT,NOT_READY


  # SIM Tray
  - type: sim_tray
    name: sim_tray
    key_name: s
    command: /sys/devices/platform/soc/soc:simtray/status
    pass_value: 1

  - type: recovery
    name: 1217
    key_name: G

  # WifiScan
  - type: wifi_scan
    name: wifi_scan
    key_name: G

  # 小米账号残留
  - type: account
    name: mi_account
    key_name: T

  # shipmode
  - type: ship_mode
    name: ship_mode
    key_name: K

  # OP Cust
  - type: opcust
    name: opcust
    key_name: M


expand_info:
  # Phone SN
  - type: property
    name: phone_sn
    key_name: c
    command: ro.ril.oem.psno

  # System image version
  - type: property
    name: version
    key_name: d
    command: ro.build.version.incremental

  # IMEI1
  - type: telephony
    name: imei1
    key_name: e

  # IMEI2
  - type: telephony
    name: imei2
    key_name: f

  # Bluetooth address
  - type: address
    name: bluetooth_address
    key_name: h
    command: ro.vendor.ril.oem.btmac

  # WiFi address
  - type: address
    name: wifi_address
    key_name: i
    command: getprop ro.vendor.ril.oem.wifimac

  # CPU id
  - type: property
    name: cpu_id
    key_name: k
    command: ro.boot.cpuid

  # Storage id
  - type: storage
    name: storage_id
    key_name: l
    params:
      storage_id_path: /sys/class/mi_memory/mi_memory_device/ufshcd0/dump_string_desc_serial

  # tzProvision
  - type: security
    name: tz_key
    key_name: m

  # Hardware version
  - type: property
    name: hardware_version
    key_name: n
    command: ro.boot.hwversion

  # Maximum CPU frequency
  - type: cpu_frequency
    name: cpu_frequency
    key_name: p
    params:
      core_number: 8
      useHz: true

  # Memory size
  - type: storage
    name: memory_size
    key_name: q

  # Storage size
  - type: storage
    name: storage_size
    key_name: r

  # Project code
  - type: code_name
    name: code_name
    key_name: s
    params:
      23077RABDC: M19
      23076RA4BC: M19
      23076RN4BI: M19
      23076RN8DY: M19
      23076PC4BI: M19P
      23076RA4BR: M19
      XIG03: M19
      23130ZL2GE: M19
       
  # MIUI cust image version
  # Optional
  - type: property
    name: cust_version
    key_name: T
    command: ro.miui.business.version
